// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/admin-redesign/GlassyPremium.tsx": () => import("../components/mockups/admin-redesign/GlassyPremium.tsx"),
  "./components/mockups/admin-redesign/OperatorHud.tsx": () => import("../components/mockups/admin-redesign/OperatorHud.tsx"),
  "./components/mockups/admin-redesign/SidebarSaas.tsx": () => import("../components/mockups/admin-redesign/SidebarSaas.tsx")
};
