// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/admin-redesign/GlassyPremium.tsx": () => import("../components/mockups/admin-redesign/GlassyPremium.tsx"),
  "./components/mockups/admin-redesign/OperatorHud.tsx": () => import("../components/mockups/admin-redesign/OperatorHud.tsx"),
  "./components/mockups/admin-redesign/SidebarSaas.tsx": () => import("../components/mockups/admin-redesign/SidebarSaas.tsx"),
  "./components/mockups/create-redesign/CompactInline.tsx": () => import("../components/mockups/create-redesign/CompactInline.tsx"),
  "./components/mockups/create-redesign/PresetTemplates.tsx": () => import("../components/mockups/create-redesign/PresetTemplates.tsx"),
  "./components/mockups/create-redesign/ScenarioWizard.tsx": () => import("../components/mockups/create-redesign/ScenarioWizard.tsx"),
  "./components/mockups/builds-redesign/CommandCockpit.tsx": () => import("../components/mockups/builds-redesign/CommandCockpit.tsx"),
  "./components/mockups/builds-redesign/InventoryFirst.tsx": () => import("../components/mockups/builds-redesign/InventoryFirst.tsx"),
  "./components/mockups/builds-redesign/OpsPipeline.tsx": () => import("../components/mockups/builds-redesign/OpsPipeline.tsx")
};
